<template>
  <div class="app">
    <!-- Navigation Bar -->
    <header class="header_container" :class="{ 'header_visible': showNavbar }">
      <div class="header_logo">
        <a href="#" class="header_logoLink typo-flow-caption" aria-label="Refresh Page">
          <img :src="getAssetPath('loop-logo.png')" alt="Loop" class="logo-image">
        </a>
      </div>
      <div class="header_jumpLinks">
        <a href="#overview" class="typo-flow-text">Overview</a>
        <a href="#capabilities" class="typo-flow-text">Features</a>
        <a href="#gallery" class="typo-flow-text header_isActive">Life Loop</a>
      </div>
      <!-- Removed the header_navContainer with community and more options icons -->
    </header>

    <main>
      <!-- Hero Section - Simplified to show only large logo -->
      <section id="hero" class="hero_hero">
        <div class="hero_heroContent">
          <div class="hero_flowEffect hero_animationDone">
            <div class="js-flowContainer hero_flowContainer">
              <div class="hero_flowEffectImg">
                <div class="hero-logo-container">
                  <img :src="getAssetPath('loop-logo.png')" alt="Loop" class="hero-logo">
                </div>
                <div class="hero-subtitle">
                  Loop crafts your story. You direct life.
                </div>
                <div class="hero-cta">
                  <button class="invitation-btn">Apply for invitation code</button>
                  <div class="hero-branding">
                    <span class="typo-small-details">From LoopAI, for the future.</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="hero_videoBackground">
          <video 
            class="hero_video" 
            autoplay 
            muted 
            loop 
            playsinline
            :src="getVideoPath('RNDR_TunnelVidoes_stretched_005_1440x1080.mp4')"
          >
            <source :src="getVideoPath('RNDR_TunnelVidoes_stretched_005_1440x1080.mp4')" type="video/mp4">
            Your browser does not support the video tag.
          </video>
        </div>
      </section>

      <!-- Spacer Text -->
      <section id="spacer-text" class="spacer-text_spacerText">
        <div class="spacer-text_title">
          <h2 class="typo-flow-subtitle">In Loop, life has no fixed script.</h2>
        </div>
        <div class="spacer-text_copy">
          <p class="typo-flow-text">Your choices will be generated by AI for the next wave. Every playback is a unique life experience that belongs to you.</p>
        </div>
      </section>

      <!-- Video Display Section -->
      <section class="video-section_videoSection" id="overview" data-section="overview">
        <div class="video-section_anchorTarget"></div>
        <!-- Removed the backgroundImageContainer with Section Background -->
        <div class="video-section_videoContainer">
          <div class="video-section_videoWrapper">
            <button aria-label="Play video" class="video-section_posterContainer" @click="playMainVideo">
              <video 
                ref="mainVideo"
                :autoplay="isMainVideoPlaying" 
                :loop="false"
                :muted="isVideoMuted"
                playsinline 
                preload="auto"
                :poster="getAssetPath('id=overview封面.png')"
                :src="currentVideoSrc"
                @ended="onMainVideoEnded"
              ></video>
              <div class="video-section_playIcon" v-if="!isMainVideoPlaying"></div>
              <!-- YouTube style volume control button -->
              <div class="video-section_volumeControl" v-if="isMainVideoPlaying">
                <button 
                  class="volume-btn"
                  @click="toggleMute"
                  :aria-label="isVideoMuted ? 'Unmute' : 'Mute'"
                >
                  <span class="material-icons" v-if="!isVideoMuted">volume_up</span>
                  <span class="material-icons" v-else>volume_off</span>
                </button>
              </div>
            </button>
          </div>
        </div>
      </section>

      <!-- Features Display -->
      <section class="capabilities_capabilities" id="capabilities" data-section="capabilities">
        <div class="capabilities_contentContainer">
          <div class="capabilities_topBorder"></div>
          <div class="capabilities_titlesContainer">
            <div 
              v-for="(capability, index) in capabilities" 
              :key="index"
              class="capabilities_groupTitle typo-flow-subtitle"
              :class="{ 'capabilities_selected': selectedCapability === index }"
            >
              <button @click="selectCapability(index)">{{ capability.title }}</button>
            </div>
          </div>
          <div class="capabilities_copyContainer typo-flow-text">
            <div 
              v-for="(capability, index) in capabilities" 
              :key="index"
              class="capabilities_groupCopy"
              :class="{ 'capabilities_selected': selectedCapability === index }"
              :aria-hidden="selectedCapability !== index"
            >
              {{ capability.description }}
            </div>
          </div>
          <div>
            <div class="swiper capabilities_swiper" ref="capabilitiesSwiper">
              <div class="swiper-wrapper">
                <div 
                  v-for="(video, index) in capabilityVideos" 
                  :key="index"
                  class="swiper-slide"
                >
                  <div class="capabilities_slideImageContainer">
                    <video autoplay loop muted playsinline preload="auto">
                      <source :src="getVideoPath(video)" type="video/mp4">
                    </video>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- Life Loop Gallery -->
      <section class="gallery_gallery" id="gallery">
        <div class="gallery_header">
          <h2 class="gallery_title_large">Life Loop</h2>
        </div>
        <div class="gallery_gradientBlurTop">
          <div></div><div></div><div></div><div></div>
        </div>
        <div class="gallery_gradientBlurBottom">
          <div></div><div></div><div></div><div></div>
        </div>
        <div class="gallery_gradientDarkenerTop"></div>
        <div class="gallery_gradientDarkenerBottom"></div>
        <div class="gallery_items">
          <div v-for="(column, columnIndex) in galleryColumns" :key="columnIndex" class="gallery_column">
            <div :data-direction="column.direction" class="gallery_columnInner">
              <div v-for="(item, itemIndex) in column.items" :key="itemIndex" class="gallery_item">
                <div class="gallery_media">
                  <div class="phone_mockup">
                    <img :src="getAssetPath('iphone-样机.png')" alt="iPhone Mockup" class="phone_frame">
                    <div class="phone_screen">
                      <video autoplay loop muted playsinline preload="auto" :src="getNewVideoPath(item.video)">
                      </video>

                    </div>
                  </div>
                </div>
                <span class="gallery_name">{{ item.name }}</span>
              </div>
            </div>
          </div>
        </div>
        <!-- Removed the Loop TV button -->
      </section>

      <!-- Footer -->
      <section class="footer_footer">
        <div class="footer_contentContainer">
          <div class="footer_disclaimer typo-material-body-small">
            Disclaimer: AI output may contain inaccurate or inappropriate content.
          </div>
          <div class="footer_linksSection">
            <a href="#" target="_blank" rel="noreferrer" class="footer_link typo-material-body-small">Privacy Policy</a>
            <a href="#" target="_blank" rel="noreferrer" class="footer_link typo-material-body-small">Terms of Service</a>
          </div>
          <div class="footer_branding">
            <span class="typo-small-details">From LoopAI, for the future.</span>
          </div>
        </div>
      </section>
    </main>
  </div>
</template>

<script>
import { ref, onMounted, onUnmounted } from 'vue'
import { Swiper, SwiperSlide } from 'swiper/vue'
import 'swiper/css'

export default {
  name: 'App',
  components: {
    Swiper,
    SwiperSlide
  },
  setup() {
    const heroCanvas = ref(null)
    const mainVideo = ref(null)
    const capabilitiesSwiper = ref(null)
    const isMainVideoPlaying = ref(false)
    const selectedCapability = ref(0)
    const showNavbar = ref(false)
    const isVideoMuted = ref(false)
    const shouldPlaySequence = ref(false)
    const currentVideoSrc = ref('视频资源新/loopai.mp4')
    const isPlayingReviewVideo = ref(false)

    // Features data
    const capabilities = ref([
      {
        title: 'AI Narrative Engine',
        description: 'Our self-developed AI narrative engine instantly understands your choice intentions. It integrates multimodal video generation, style rendering, and coherence maintenance technologies to calculate and generate the next unique storyline before you make your decision, breaking free from the linear constraints of traditional videos.'
      },
      {
        title: 'Parallel Universe Roaming',
        description: 'Every choice creates a brand new parallel universe. Loop\'s unique "story tree" system visualizes all your decision paths. You can return to any key node at any time to explore another unfinished path, truly achieving full control over the story dimension and experiencing every possibility.'
      },
      {
        title: 'Interactive Co-director',
        description: 'All viewers can also participate in your life choices. AI automatically completes millions of branching storylines based on choices. Everyone is an audience, but also a creator and promoter of content.'
      }
    ])

    // Feature videos
    const capabilityVideos = ref([
      '01_Ingredients_Edit 1 16x9_250516d.mp4',
      '02_Ingredients to video_Edit03_16x9_250516e.mp4',
      '03 Frames to Video_250516a.mp4',
      '04 Scene Builder_250513c_1.mp4',
      '05_JumpTo_250516a.mp4',
      '06_Extend_5mb_250519a.mp4',
      '07_CameraControls_Edit02 16x9_250516e.mp4',
      '08_VEO_Cinematic_Edit01_16x9_250516e.mp4'
    ])

    // Gallery data - using new video filenames with English translations
    const galleryColumns = ref([
      {
        direction: 'down',
        items: [
          { name: 'The interstellar war is in full swing, your fleet is about to depart, how do you prepare to resist the stormtrooper?', video: '星际战争如火如荼，你的舰队即将出发，你准备如何抵抗风暴兵团？.mp4' },
          { name: 'This is the girl I met today, where should I take her?', video: '这是今天新认识的女孩，我需要请她去哪里？.mp4' },
          { name: 'Today is your first day as a killer, what are you thinking?', video: '今天是你成为杀手的第一天，你在想什么？.mp4' },
          { name: 'You wake up in a snow country and are forced to enlist, which profession do you choose?', video: '一觉醒来你来到雪国被迫入伍，你选择那个职业？.mp4' }
        ]
      },
      {
        direction: 'up',
        items: [
          { name: 'The otter next door is knocking anxiously, should I open the door?', video: '隔壁的水獭在焦急敲门，我应不应该开门？.mp4' },
          { name: 'A UFO is flying at low altitude, have aliens invaded?', video: '一驾UFO在低空飞行，外星人入侵了吗？.mp4' },
          { name: 'When you were 15, you met the future US president who came to your hometown in the 80s to perform for a living. What are you going to do?', video: '15岁的你遇到未来美国总统来到80年代你的家乡卖艺求生，你准备做什么？.mp4' },
          { name: 'The ant army is hoarding food to prepare for counterattack, who is their enemy?', video: '蚂蚁军团正在囤积食物准备反击，它们敌人是谁？.mp4' }
        ]
      },
      {
        direction: 'down',
        items: [
          { name: 'A strange case in the forest on videotape, why is this person live streaming?', video: '一件森林里的诡异案件录像带，为什么会是这个人在直播？.mp4' },
          { name: 'You picked up Captain Jack\'s Black Pearl sealed in a water droplet, what are you going to do?', video: '你捡到了杰克船长的黑珍珠号被封锁在水滴中，你准备怎么做？.mp4' },
          { name: 'This little pig, where is it preparing to parachute to escape?', video: '这个小猪，它准备跳伞逃亡到哪里？.mp4' }
        ]
      }
    ])

    // Methods
    const getAssetPath = (path) => {
      return path
    }

    const getVideoPath = (filename) => {
      return `视频资源/${filename}`
    }

    const getNewVideoPath = (filename) => {
      return `视频资源新/${filename}`
    }

    const playMainVideo = () => {
      if (mainVideo.value) {
        // 重置到开始状态
        shouldPlaySequence.value = true
        isPlayingReviewVideo.value = false
        currentVideoSrc.value = '视频资源新/loopai.mp4'
        isMainVideoPlaying.value = true
        
        // 确保视频不循环
        mainVideo.value.loop = false
        
        // 等待视频源更新后再播放
        setTimeout(() => {
          if (mainVideo.value) {
            mainVideo.value.load() // 重新加载视频
            mainVideo.value.play()
          }
        }, 100)
      }
    }

    const onMainVideoEnded = () => {
      console.log('视频播放结束', { shouldPlaySequence: shouldPlaySequence.value, isPlayingReviewVideo: isPlayingReviewVideo.value })
      
      if (shouldPlaySequence.value && !isPlayingReviewVideo.value) {
        // 第一个视频 loopai.mp4 播放完毕，切换到 loop review.mov
        console.log('切换到 loop review.mov')
        isPlayingReviewVideo.value = true
        currentVideoSrc.value = '视频资源新/loop review.mov'
        
        // 等待视频源更新后播放
        setTimeout(() => {
          if (mainVideo.value) {
            mainVideo.value.load() // 重新加载视频
            mainVideo.value.play()
          }
        }, 100)
      } else if (shouldPlaySequence.value && isPlayingReviewVideo.value) {
        // loop review.mov 播放完毕，重新开始循环
        console.log('重新开始播放 loopai.mp4')
        isPlayingReviewVideo.value = false
        currentVideoSrc.value = '视频资源新/loopai.mp4'
        
        setTimeout(() => {
          if (mainVideo.value) {
            mainVideo.value.load() // 重新加载视频
            mainVideo.value.play()
          }
        }, 100)
      }
    }

    const selectCapability = (index) => {
      selectedCapability.value = index
    }

    const toggleMute = () => {
      isVideoMuted.value = !isVideoMuted.value
      if (mainVideo.value) {
        mainVideo.value.muted = isVideoMuted.value
      }
    }

    // Scroll listener to control navbar display
    const handleScroll = () => {
      const scrollTop = window.pageYOffset || document.documentElement.scrollTop
      // Show navbar when scrolled past 50% of viewport height
      showNavbar.value = scrollTop > window.innerHeight * 0.5
    }

    onMounted(() => {
      window.addEventListener('scroll', handleScroll)
    })

    onUnmounted(() => {
      window.removeEventListener('scroll', handleScroll)
    })

    return {
      heroCanvas,
      mainVideo,
      capabilitiesSwiper,
      isMainVideoPlaying,
      selectedCapability,
      showNavbar,
      capabilities,
      capabilityVideos,
      galleryColumns,
      getAssetPath,
      getVideoPath,
      getNewVideoPath,
      playMainVideo,
      selectCapability,
      isVideoMuted,
      toggleMute,
      shouldPlaySequence,
      currentVideoSrc,
      isPlayingReviewVideo,
      onMainVideoEnded
    }
  }
}
</script> 